# Generated by Django 5.2.3 on 2025-08-17 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0005_alter_subscription_course_alter_subscription_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="owner",
            new_name="user",
        ),
    ]
