# Generated by Django 5.2.3 on 2025-08-17 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0006_rename_owner_lesson_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="owner",
            new_name="user",
        ),
    ]
